turnos/apps/sistematurnos/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^nuevo/', TurnoCreate.as_view(), name='Turno_crear'),
    url(r'^listar', TurnoList.as_view(), name='Turno_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', TurnoDelete.as_view(), name='Turno_eliminar'),
    url(r'^editar/(?P<pk>\d+)/$', TurnoUpdate.as_view(), name='Turno_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', TurnoShow.as_view(), name='Turno_mostrar'),
]

turnos/turnos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sistematurnos/', include('apps.sistematurnos.urls', namespace='sistematurnos')),
]

turnos/apps/sistematurnos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# Create your models here.
class Dia(models.Model):
	id = models.AutoField(primary_key=True)
	dia = models.CharField(max_length=30, default="")
	def __str__(self):
		return '{}'.format(self.dia)

class Turno(models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=70)
	codigo = models.CharField(max_length=70, default='' )
	inicio = models.TimeField( blank=True, null=True)
	termino = models.TimeField( blank=True, null=True)
	dias = models.ManyToManyField(Dia, related_name="dias")
	def __str__(self, encoding='utf-8'):
		return '{}'.format(self.nombre)

turnos/apps/sistematurnos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from .models import *
from .form import TurnoForm



# Create your views here.
class TurnoCreate(CreateView):
	model = Turno
	form_class = TurnoForm
	template_name = 'sistematurno/turno_form.html'
	success_url = reverse_lazy('sistematurnos:Turno_listar')


class TurnoList(ListView):
	queryset = Turno.objects.order_by('id')
	template_name = 'sistematurno/turno_list.html'
class TurnoUpdate(UpdateView):
	model = Turno
	form_class = TurnoForm
	template_name = 'sistematurno/turno_form.html'
	success_url = reverse_lazy('sistematurnos:Turno_listar')

class TurnoDelete(DeleteView):
	model = Turno
	template_name = 'sistematurno/turno_delete.html'
	success_url = reverse_lazy('sistematurnos:Turno_listar')

class TurnoShow(DetailView):
	model = Turno
	template_name = 'sistematurno/turno_show.html'

turnos/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>{% block title %}Document {% endblock %}</title>
</head>

<body>

		{% block navbar %}
		<div class="bs-docs-section clearfix">
			<div class="row">
				<div class="col-lg-12">
					<div class="bs-component">
						<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
							<a class="navbar-brand" href="{% url 'sistematurnos:Turno_listar' %}">Sistema de Turnos</a>
							<div class="collapse navbar-collapse" id="navbarSupportedContent">
								<ul class="navbar-nav mr-auto">
									
									<li class="nav-item dropdown">
										<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
											data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											turnos
										</a>
										<div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{% url 'sistematurnos:Turno_crear' %}">Agregar</a>
                                            <a class="dropdown-item" href="{% url 'sistematurnos:Turno_listar' %}">Listado</a>
										</div>
									</li>
									<li class="nav-item">
                                        <a class="nav-link" href="https://www.linkedin.com/in/fbadillaore/"
													onclick="pageTracker._link(this.href); return false;">Conoce al
													Desarrollador</a>
									</li>
								</ul>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

		{% endblock %}
<div class="p-3 mb-2 bg-dark text-white">

		{% block content %}
    
	<h4>	Bloque de contenido		</h4>

		{% endblock %}


		{% block footer %}
		{% endblock%}
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
	</script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
		integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
	</script>

	{% block extrajs %}
	{% endblock %}

</div>
</body>

</html>

turnos/templates/sistematurno/turno_delete.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
		<div class="row justify-content-md-center">
		<div class="col-md">
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombres }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'sistematurnos:Turno_listar' %}">Cancelar</a>
</form>
</div>
        </div>
        </div>
{% endblock %}

turnos/templates/sistematurno/turno_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
		<div class="row justify-content-md-center">
		<div class="col-md">
<form method="post" content='text/html; charset=UTF-8'>
	{% csrf_token %}
	{{ form.as_p }}
    <div class="row">
    <span>Ctrl o cmd para elegir varios dias</span>
</div>
	<button class="btn btn-success" type="submit">Guardar</button>
	<a class= "btn btn-primary" href="{% url 'sistematurnos:Turno_listar' %}">Cancelar</a>
</form>
</div>
</div>  
</div>
{% endblock %}

turnos/templates/sistematurno/turno_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
		<div class="row justify-content-md-center">
		<div class="col-md">
<table class="table table-hover table-dark">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>codigo</td>
            <td>Dias</td>
			<td>inicio</td>
			<td>termino</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for turno in object_list %}
		<tr>
			<td>{{ turno.id }}</td>
			<td>{{ turno.nombre }}</td>
			<td>{{ turno.codigo }}</td>
            <td>{{ turno.dias.all|join:','}}</td>
			<td>{{ turno.inicio }}</td>
			<td>{{ turno.termino }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'sistematurnos:Turno_mostrar' turno.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'sistematurnos:Turno_editar' turno.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'sistematurnos:Turno_eliminar' turno.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de Turnos</h1>
		{% endif %}
	</tbody>
</table>
		</div>
        </div>
        </div>

{% endblock%}

turnos/templates/sistematurno/turno_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
		<div class="row justify-content-md-center">
		<div class="col-md">
<p class="text-light bg-dark"><strong>identificacion: </strong>{{ object.id }} </p>
<p class="text-light bg-dark"><strong>Nombre del Turno: </strong>{{ object.nombre }} </p>
<p class="text-light bg-dark"><strong>Codigo: </strong>{{ object.codigo }} </p>
<p class="text-light bg-dark"><strong>Codigo: </strong>{{ object.dias.all|join:','}} </p>
<p class="text-light bg-dark"><strong>Fecha de Inicio: </strong>{{ object.inicio }} </p>
<p class="text-light bg-dark"><strong>Fecha de Termino: </strong>{{ object.termino }} </p>

<a class= "btn btn-success" href="{% url 'sistematurnos:Turno_listar' %}">Ok</a>
<a class= "btn btn-primary" href="{% url 'sistematurnos:Turno_editar' object.id%}">Editar</a>
<a class="btn btn-danger" href="{% url 'sistematurnos:Turno_eliminar' object.id %}">Eliminar</a>
		</div>
        </div>
        </div>
{% endblock %}